name: Update Styles and Scripts

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
        
      - name: Install dependencies
        run: bun install
    
      - name: Update Styles and Scripts
        run: bun update.js
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Styles and Scripts
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: AltStore Sources